import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const word = "wordle";
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-200 text-white h-12 p-2 flex items-center justify-end">
          {word.split("").map((letter, index) => (
            <div
              key={index}
              className="bg-green w-8 h-8 mx-1 flex items-center justify-center rounded-sm"
            >
              {letter}
            </div>
          ))}
        </header>{" "}
        {children}
      </body>
    </html>
  );
}
